from __future__ import annotations
from abc import ABC, abstractmethod
from datetime import datetime

from app.domain.entities import Priority, TodoItem


class ITodoView(ABC):
    # Отрисовка
    @abstractmethod
    def show_todos(self, todos: list[TodoItem]) -> None: ...
    @abstractmethod
    def add_todo(self, item: TodoItem) -> None: ...
    @abstractmethod
    def update_todo(self, item: TodoItem) -> None: ...
    @abstractmethod
    def remove_todo(self, todo_id: int) -> None: ...

    @abstractmethod
    def show_error(self, message: str) -> None: ...

    @abstractmethod
    def get_input_title(self) -> str: ...
    @abstractmethod
    def get_input_priority(self) -> Priority: ...
    @abstractmethod
    def get_input_deadline(self) -> datetime | None: ...
    @abstractmethod
    def get_selected_id(self) -> int | None: ...
    @abstractmethod
    def get_filter(self) -> str: ...
    @abstractmethod
    def clear_input(self) -> None: ...

    @abstractmethod
    def show_edit_panel(self, item: TodoItem) -> None: ...
    @abstractmethod
    def hide_edit_panel(self) -> None: ...